version: '3.8'

services:

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web-analyzer-backend
    restart: unless-stopped
    ports:
      - "9090:9090"  # Added port mapping to expose service to host
    environment:
      - PORT=9090
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=web_analyzer
      - MONGO_COLLECTION=analyses
      - REQUEST_TIMEOUT=30
      - KEYCLOAK_URL=http://localhost:8080
      - KEYCLOAK_REALM=web-analyzer
      - KEYCLOAK_CLIENT_ID=web-analyzer-backend
      # Removed KEYCLOAK_CLIENT_SECRET as we're using internal DB without secrets
    depends_on:
      - mongo
      - keycloak
    networks:
      - web-analyzer-network

  # MongoDB service
  mongo:
    ports:
      - "27017:27017"
    image: mongo:latest
    container_name: web-analyzer-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - web-analyzer-network

# Keycloak service
  keycloak:
    ports:
      - "8080:8080"
      - "9000:9000"
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: web-analyzer-keycloak
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
      - KC_HOSTNAME_STRICT=false
      #- KC_HTTP_RELATIVE_PATH=/auth
    command:
      - start-dev
    networks:
      - web-analyzer-network

networks:
  web-analyzer-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local