version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-analyzer-backend
    restart: unless-stopped
    ports:
      - "9090:9090"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://host.docker.internal:27017
      - MONGO_DB=web_analyzer
      - MONGO_COLLECTION=analyses
      - REQUEST_TIMEOUT=30
      - KEYCLOAK_URL=http://host.docker.internal:8080/auth
      - KEYCLOAK_REALM=web-analyzer
      - KEYCLOAK_CLIENT_ID=web-analyzer-backend
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    depends_on:
      - mongo
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local